project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    contents:
      - section: "Metagenome analysis"
        contents:
          - text: "Variant counts, CAP and tSNE"
            file: Analysis1.qmd
          - text: "Parallelism"
            file: Analysis2.qmd
          - text: "Parallel gene plots (all groups)"
            file: Analysis4.qmd
          - text: "Parallel gene plots (meas_env and strep)"
            file: Analysis5.qmd
          - text: "Streptomycin resistance related genes"
            file: Analysis3.qmd
          - text: "Redundancy analysis (RDA)"
            file: Analysis7.qmd

format:
  html:
    # when printing dataframes use rmarkdown::paged_table())
    df-print: paged
    